baseURL = ''
languageCode = 'en-us'
title = 'André Martins'
staticDir = ['assets/images', 'assets/js', 'assets/pdf']

disableKinds = ["taxonomyTerm"]
enableRobotsTXT = true

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
  js = ["index.js"]
